### ISSUE TITLE
Consumer key input is not obvious

### ISSUE THREAD

**Issue by jordanrolph** [SeanBE/pocket-retro#30]
Hey, I had an UX issue when entering my consumer key (on first launch)

I like the styling but I could not find the invisible input field, meaning typing did nothing. I eventually managed to focus the input by clicking around the screen.

Maybe the input should be auto-focussed?

**Comment by SeanBE** [comment]
Thanks for this issue! The input is auto-focused but you picked up on a CSS bug of mine. Original intention was for any mouse click within the content div to focus on the invisible input but this was placed on the wrong div (facepalm + lack of testing)

Since we are unable to manipulate the text cursor, my original solution was a blinking span at the end of visible text span. I see how this can cause confusion when you start moving the underlying text cursor on the invisible input. 

New implementation fixes the focus click on the parent div and using the caret position of the input field to place the blinking span between the characters. 

You can pull the latest from dockerhub now (https://hub.docker.com/r/seanbe/pocket_retro)
